apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend 
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: python-backend-application
        image: <give your image>
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: python-backend-service
spec:
  selector:
    app: backend
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
